spring.application.name=entrega_tech_lab
spring.datasource.url=jdbc:mysql://localhost:3306/practicatechlab
spring.datasource.username=root
spring.datasource.password=Pier.5030
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=9090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=oIvyQVVVx1S8FC8r1X2M50ShA5n4A7Bv6vS+KX3Qzv0v0G0L9Vw7F9t1O2mR8VQd0iD0fS8l9vV8mM6P3hL1KJ2w2Q==
jwt.expiration=86400000
logging.level.org.springframework.web=TRACE